image: Ubuntu2004
version: 1.0.{build}

only_commits:
  files:
    - projects/core/

environment:

  OUTPUT_FOLDER: "dist/@message-bus/core"

  # API Key used for deploying to MyGet npm.
  API_KEY_MY_GET:
    secure: 0HqMlO4KT03m1Obda0ta46zbO1EgtiSouotet2O7J7QU5SMEJfrv+GgM0cuNPL9l

  API_KEY_NPM:
    secure: nIeG09zqUgJaPWS4YclqB4s/BDnoy0DrNiwvLl+p9eQZknDycbInyKs4uEF6JBbk

for:
  -
    branches:
      only:
        - angular-13/main
        - /angular-13\/features\/.+/
        - angular-13/release
    environment:
      NODEJS_VERSION: "17.2.0"

  -
    branches:
      only:
        - angular-11/main
        - /angular-11\/features\/.+/
        - angular-11/release
    environment:
      NODEJS_VERSION: "13.7.0"

install:

  # Get the latest stable version of Node.js.
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

  - nvm install $env:NODEJS_VERSION

  - nvm use $env:NODEJS_VERSION

  # Install npm package.
  - npm install --loglevel=error

build_script:
  # Build application in production mode.
  - npm run build:lib

#test_script:
  # Run unit test for core project.
#  - protractor projects/core/e2e/protractor.conf.js

deploy_script:

  - sh: |
      DEPLOYMENT_BRANCH_REGEX="^angular-\d+\/release$"

      IF [ "$APPVEYOR_REPO_BRANCH" =~ "$DEPLOYMENT_BRANCH_REGEX" ]
      THEN
        echo //registry.npmjs.org/:_authToken=%API_KEY_NPM% >> ./dist/@message-bus/core/.npmrc
        npm publish dist/@message-bus/core --dry-run
      FI
