version: 1.0.{build}

only_commits:
  files:
    - projects/core/

environment:

  OUTPUT_FOLDER: "dist/@message-bus/core"

  # API Key used for deploying to MyGet npm.
  API_KEY_MY_GET:
    secure: 0HqMlO4KT03m1Obda0ta46zbO1EgtiSouotet2O7J7QU5SMEJfrv+GgM0cuNPL9l

  API_KEY_NPM:
    secure: nIeG09zqUgJaPWS4YclqB4s/BDnoy0DrNiwvLl+p9eQZknDycbInyKs4uEF6JBbk

install:

  - ps: >-
      if ($APPVEYOR_REPO_BRANCH -Match "^angular-13.*$") {
        $env:NODEJS_VERSION="17.2.0"
      } elseif ($APPVEYOR_REPO_BRANCH -Match "^angular-11.*$") {
        $env:NODEJS_VERSION="13.7.0"
      }

  - ps: Install-Product node $env:NODEJS_VERSION

  # Install npm package.
  - npm install --loglevel=error

build_script:
  # Build application in production mode.
  - npm run build:lib

#test_script:
  # Run unit test for core project.
#  - protractor projects/core/e2e/protractor.conf.js

deploy_script:

  - ps: >-
      $env:DEPLOYMENT_BRANCH_REGEX="^angular-\d+\/release$"

      if ("$APPVEYOR_REPO_BRANCH" -Match "$DEPLOYMENT_BRANCH_REGEX") {
        echo //registry.npmjs.org/:_authToken=$env:API_KEY_NPM >> ./dist/@message-bus/core/.npmrc
        npm publish dist/@message-bus/core --dry-run
      }
